### ISSUE TITLE
ChEMBL SPARQL query

### ISSUE THREAD

**Issue by YojanaGadiya** [idsm-src/chemweb#1]
Dear IDSM team,

I wanted to know if there is a possibility to query the ChEMBL RDF graph similarly to the PubChem one shown [here](https://idsm.elixir-czech.cz/chemweb/). If yes, please can you provide the link to an example query and the data model?

Regards,
Yojana Gadiya

**Comment by galgonek** [comment]
Dear Yojana,

Yes, ChEMBL RDF is also included in IDSM, specifically in the graph `<http://rdf.ebi.ac.uk/dataset/chembl>`.

The lists of predicates and classes used by CHEMBL RDF can be obtained by the following SPARQL queries:

```sparql
SELECT DISTINCT ?PREDICATE
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE
{
  ?SUBJECT ?PREDICATE ?OBJECT
}
ORDER BY ?PREDICATE
```

```sparql
SELECT DISTINCT ?CLASS
FROM <http://rdf.ebi.ac.uk/dataset/chembl>
WHERE
{
  ?SUBJECT a ?CLASS
}
ORDER BY ?CLASS
```

IDSM currently contains CHEMBL RDF version 34. Unfortunately, the EBI team does not provide a description of the data model for this version. The last description was provided for [version 28](https://ftp.ebi.ac.uk/pub/databases/chembl/ChEMBL-RDF/28.0/chembl_rdf_full_schema.png). However, the differences between these versions should be minimal. Alternatively, some information can also be obtained from Figure 2 in [IDSM ChemWebRDF: SPARQLing small-molecule datasets](https://doi.org/10.1186/s13321-021-00515-1) (blue nodes are relevant for ChEMBL RDF).

There is probably no official set of example SPARQL queries for CHEMBL RDF at this time. However, the queries published here should probably work: https://github.com/BiGCAT-UM/ChEMBL-SPARQL-Queries.

Regards,
Jakub

**Comment by YojanaGadiya** [comment]
Perfect! Thank you for your response. I will look into this and if any issues will get back to you. For now, closing the issue.
